<?php
declare(strict_types=1);

namespace FreireH\CatalogRuleGrid\Ui\DataProvider\Grid;

use Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider;

class ListingDataProvider extends DataProvider
{
    public function getSearchResult()
    {
        $result = parent::getSearchResult(); // TODO: Change the autogenerated stub
        $column = 'rule_id';

        $adminSubQuery = new \Zend_Db_expr("(
                select rule_id, GROUP_CONCAT(name ORDER BY name SEPARATOR ', ') as website_id
                from catalogrule_website left join store_website ON catalogrule_website.website_id = store_website.website_id
                group by rule_id
                )");

        $result->getSelect()->joinLeft(
            ['website' => $adminSubQuery],
            'website.' . $column . ' = main_table.' . $column,
            ['website_id' => 'website.website_id']
        );

//        die($result->getSelectSql(1));

        return $result;
    }
}
