<?php
declare(strict_types=1);

namespace FreireH\CatalogRuleGrid\Ui\DataProvider\Grid;

use Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider;

class ListingDataProvider extends DataProvider
{
    public function getSearchResult()
    {
        $result = parent::getSearchResult(); // TODO: Change the autogenerated stub
        $column = 'rule_id';

        $adminSubQuery = new \Zend_Db_expr("(
                select rule_id, GROUP_CONCAT(website_id ORDER BY website_id SEPARATOR ',') as website_id
                from catalogrule_website
                group by rule_id
                )");

        $result->getSelect()->joinLeft(
            ['website' => $adminSubQuery],
            'website.' . $column . ' = main_table.' . $column,
            ['website_id' => 'website.website_id']
        );

//        die($result->getSelectSql(1));

        return $result;
    }
}
